### ISSUE TITLE
Inject AWS-provided Apache Client for Xray

### ISSUE THREAD

**Issue by tvanhens** [Stedi-Public-Archive/clj-http#1]

**Comment by grammati** [comment]
clj-http recently added a feature that might make this easier: https://github.com/dakrone/clj-http/commit/ff91bc61684db7254ba25912fb79dca64fb20555

**Comment by grammati** [comment]
In places where we use clj-http to make HTTP calls, we are not getting x-ray tracing.

AWS provides a forked version of the Apache HTTP client (which is what clj-http uses internally) that gives you x-ray support for free.

We need to slighly modify our usage of clj-http so that is uses an instance of the AWS-provided HTTP client.

See: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-httpclients.html

Note: we need to make sure that doing this doesn't break local dev when you don't have an x-ray-daemon running.

**Comment by tvanhens** [comment]
One idea here is to dispatch based on some environment variable that should only be available in a lambda runtime context. So we'd use the regular apache d
